"""v2.3 §19~§23：对话表达层（Question Planner / Response Planner / Conversation State）。"""
from .conversation_state import (
    ConversationState,
    get_conversation_state,
    known_question,
    reset_conversation_state,
    stage_from_status,
    update_conversation_state,
)
from .question_planner import QuestionPlan, plan_question
from .question_order import next_in_order, shuffled_slots
from .question_flow import (
    ASK_POOL,
    HARD_SLOTS,
    hard_recap_pending,
    next_question_plan,
    pass1_complete,
    pass1_pending,
    random_order,
    why_for,
)
from .response_coordinator import ResponseCoordinator
from .response_planner import ResponsePlan, plan_response, reassure_line
from .action import (
    ACK_ONLY,
    ANSWER_AND_ASK,
    ASK,
    CLARIFY,
    CONFIRM,
    DIRECT_ANSWER,
    DialogueDecision,
    RECOMMEND,
    decide_dialogue_action,
)
from .ab_test import compare_strategies, run_strategy
from .final_guard import (
    FinalResponseGuard,
    GuardResult,
    QuestionCandidate,
    finalize_response,
)
from .grounded_facts import (
    GroundedFact,
    build_grounded_facts,
)
from .policy import (
    ANSWER_ONLY,
    ANSWER_THEN_ASK,
    ASK_ONLY,
    CLARIFY_ONLY,
    RECOMMEND_ONLY,
    DialogueAction,
    decide_action,
    decide_speech_policy,
    question_candidates,
    rank_slots_by_value,
    select_next_question,
    should_append_requirement_question,
)
from .speech_act import (
    ANSWER_REQUIREMENT,
    CASUAL,
    CUSTOMER_QUESTION,
    DELIVERY_QUESTION,
    MULTI_INTENT,
    NEW_REQUIREMENT,
    PRICE_QUESTION,
    PRODUCT_QUESTION,
    SpeechActResult,
    detect_speech_act,
)
from .response_context import ResponseContext
from .response_generator import (
    DEFAULT_STRATEGY,
    NATIVE_SYSTEM_PROMPT,
    STRATEGY_NATIVE,
    STRATEGY_TEMPLATE_POLISH,
    build_context,
    compose_from_context,
    generate_response,
    get_response_strategy,
    llm_available,
    reset_llm_breaker,
    set_response_strategy,
)
from .response_validator import (
    ResponseValidation,
    compute_metrics,
    echo_ratio,
    questionnaire_pattern,
    repeated_question_slot,
    validate_response,
)

__all__ = [
    "ACK_ONLY",
    "ANSWER_AND_ASK",
    "ANSWER_ONLY",
    "ANSWER_REQUIREMENT",
    "ANSWER_THEN_ASK",
    "ASK_POOL",
    "ASK_ONLY",
    "ASK",
    "CASUAL",
    "CLARIFY",
    "CLARIFY_ONLY",
    "CONFIRM",
    "ConversationState",
    "CUSTOMER_QUESTION",
    "DELIVERY_QUESTION",
    "DEFAULT_STRATEGY",
    "DIRECT_ANSWER",
    "DialogueAction",
    "DialogueDecision",
    "FinalResponseGuard",
    "GuardResult",
    "GroundedFact",
    "HARD_SLOTS",
    "MULTI_INTENT",
    "NEW_REQUIREMENT",
    "PRICE_QUESTION",
    "PRODUCT_QUESTION",
    "QuestionPlan",
    "QuestionCandidate",
    "RECOMMEND",
    "RECOMMEND_ONLY",
    "ResponseCoordinator",
    "ResponseContext",
    "ResponsePlan",
    "ResponseValidation",
    "SpeechActResult",
    "NATIVE_SYSTEM_PROMPT",
    "STRATEGY_NATIVE",
    "STRATEGY_TEMPLATE_POLISH",
    "build_context",
    "build_grounded_facts",
    "compose_from_context",
    "compare_strategies",
    "compute_metrics",
    "decide_action",
    "decide_dialogue_action",
    "decide_speech_policy",
    "detect_speech_act",
    "echo_ratio",
    "finalize_response",
    "generate_response",
    "get_response_strategy",
    "llm_available",
    "get_conversation_state",
    "hard_recap_pending",
    "known_question",
    "next_in_order",
    "next_question_plan",
    "pass1_complete",
    "pass1_pending",
    "plan_question",
    "plan_response",
    "random_order",
    "reassure_line",
    "questionnaire_pattern",
    "question_candidates",
    "rank_slots_by_value",
    "repeated_question_slot",
    "reset_conversation_state",
    "reset_llm_breaker",
    "run_strategy",
    "select_next_question",
    "set_response_strategy",
    "should_append_requirement_question",
    "shuffled_slots",
    "stage_from_status",
    "update_conversation_state",
    "validate_response",
    "why_for",
]
