"""v2.3 §19~§23：对话表达层（Question Planner / Response Planner / Conversation State）。"""
from .conversation_state import (
    ConversationState,
    get_conversation_state,
    known_question,
    reset_conversation_state,
    stage_from_status,
    update_conversation_state,
)
from .question_planner import QuestionPlan, plan_question
from .question_order import next_in_order, shuffled_slots
from .question_flow import (
    ASK_POOL,
    HARD_SLOTS,
    hard_recap_pending,
    next_question_plan,
    pass1_complete,
    pass1_pending,
    random_order,
    why_for,
)
from .response_coordinator import ResponseCoordinator
from .response_planner import ResponsePlan, plan_response, reassure_line
from .action import (
    ACK_ONLY,
    ANSWER_AND_ASK,
    ASK,
    CLARIFY,
    CONFIRM,
    DIRECT_ANSWER,
    DialogueDecision,
    RECOMMEND,
    decide_dialogue_action,
)
from .ab_test import compare_strategies, run_strategy
from .response_context import ResponseContext
from .response_generator import (
    DEFAULT_STRATEGY,
    NATIVE_SYSTEM_PROMPT,
    STRATEGY_NATIVE,
    STRATEGY_TEMPLATE_POLISH,
    build_context,
    compose_from_context,
    generate_response,
    get_response_strategy,
    llm_available,
    reset_llm_breaker,
    set_response_strategy,
)
from .response_validator import (
    ResponseValidation,
    compute_metrics,
    echo_ratio,
    questionnaire_pattern,
    repeated_question_slot,
    validate_response,
)

__all__ = [
    "ACK_ONLY",
    "ANSWER_AND_ASK",
    "ASK_POOL",
    "ASK",
    "CLARIFY",
    "CONFIRM",
    "ConversationState",
    "DEFAULT_STRATEGY",
    "DIRECT_ANSWER",
    "DialogueDecision",
    "HARD_SLOTS",
    "QuestionPlan",
    "RECOMMEND",
    "ResponseCoordinator",
    "ResponseContext",
    "ResponsePlan",
    "ResponseValidation",
    "NATIVE_SYSTEM_PROMPT",
    "STRATEGY_NATIVE",
    "STRATEGY_TEMPLATE_POLISH",
    "build_context",
    "compose_from_context",
    "compare_strategies",
    "compute_metrics",
    "decide_dialogue_action",
    "echo_ratio",
    "generate_response",
    "get_response_strategy",
    "llm_available",
    "get_conversation_state",
    "hard_recap_pending",
    "known_question",
    "next_in_order",
    "next_question_plan",
    "pass1_complete",
    "pass1_pending",
    "plan_question",
    "plan_response",
    "random_order",
    "reassure_line",
    "questionnaire_pattern",
    "repeated_question_slot",
    "reset_conversation_state",
    "reset_llm_breaker",
    "run_strategy",
    "set_response_strategy",
    "shuffled_slots",
    "stage_from_status",
    "update_conversation_state",
    "validate_response",
    "why_for",
]
