"""Common prompts module."""
from .system import SYSTEM_PROMPT, FORMAT_PROMPT
from .format import FORMAT_PROMPT as COMMON_FORMAT, JSON_FORMAT_PROMPT, LIST_FORMAT_PROMPT

__all__ = ["SYSTEM_PROMPT", "FORMAT_PROMPT", "COMMON_FORMAT", "JSON_FORMAT_PROMPT", "LIST_FORMAT_PROMPT"]
